name: Docker Image CI

on:
  push:
    tags:
      - v*

env:
  APP_NAME: qqwry-update
  DOCKERHUB_REPO: initobject/qqwry-update

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Generate App Version
      run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: |
          linux/386
          linux/amd64
          linux/arm/v5
          linux/arm/v7
          linux/arm64
          linux/mips64le
          linux/ppc64le
          linux/s390x
        push: true
        build-args: |
          APP_NAME=${{ env.APP_NAME }}
          APP_VERSION=${{ env.APP_VERSION }}
        tags: |
          ${{ env.DOCKERHUB_REPO }}:latest
          ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
